# Use root/example as user/password credentials
version: '3,8'

services:
  postgres:
    container_name: fintalk_db_container
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fintalk_db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
  